name: Build and Deploy GH Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm install

      - name: Output docs
        run: npm run docs

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs