name: Test lib

on:
  push:
    branches:
      - '*'

jobs:
  test-lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: Install dependencies
        run: npm install

      - name: Bundle
        run: npm run bundle:request --no-warnings

      - name: Test
        run: npm run test:request --no-warnings
